function [fitresult, gof] = createFit(X, subY)
%CREATEFIT(X,SUBY)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : X
%      Y Output: subY
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 06-Dec-2018 12:08:19


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( X, subY );

% Set up fittype and options.
ft = fittype( 'a*exp((-1/2)*((x-b)/c)^2)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [0 0 0];
opts.StartPoint = [3000 7 1];
opts.Upper = [16000 15 15];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'subY vs. X', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel X
ylabel subY
grid on


