function batch_selection(trans_pattern, trans_string, stack_1_string, stack_2_string, z_steps, region_size, snr_threshold)

pattern_file_struct = dir(trans_pattern);
for n = 1:numel(pattern_file_struct)
    trans_fullfile = fullfile(pattern_file_struct(n).folder, pattern_file_struct(n).name);
    stack_fullfile_1 = strrep(trans_fullfile, trans_string, stack_1_string);
    stack_fullfile_2 = strrep(trans_fullfile, trans_string, stack_2_string);
    sprintf('Processing: %s', trans_fullfile)
    spot_struct_array = spot_detection(...
        trans_fullfile, ...
        stack_fullfile_1, ...
        stack_fullfile_2, ...
        z_steps, ...
        region_size, ...
        snr_threshold ...
        );
    trans_matfile = strrep(trans_fullfile, '.tif', '.mat');
    save(trans_matfile, 'spot_struct_array', '-append');
    clear spot_struct_array
end