function croppedImage = cropImage(paddedPolygon, im)
%Crop image using bounding box derived from paddedPolygon image

props = regionprops(paddedPolygon, 'BoundingBox');
boundingBox = props.BoundingBox;
croppedImage = im(...
                                ceil(boundingBox(2)):...
                                ceil(boundingBox(2)) + boundingBox(4) - 1,...
                                ceil(boundingBox(1)):...
                                ceil(boundingBox(1)) + boundingBox(3) - 1);
