function  [height, width, num_z, num_c, file_S] = parseTileSizes(directory)
%%parseTileSizes parses the Z and channel dimensions of a Nikon Scan directory
%
%   input :
%       directory : A string variable specifying the directory to parse
%
%   output :
%       height : A scalar variable specifying the height of scan stack in
%       pixels
%
%       width : A scalar variable specifying the width of scan stack in
%       pixels
%
%       num_z : A scalar variable containing the number of z-planes in the
%       scan
%
%       num_c : A scalar varialbe containing the number of channels in the
%       scan
%
%       file_S : A structure array containing the TIF-file information.
%       Generated by calling dir.
%% Parse parameters from filenames
file_S = dir(fullfile(directory, '*.tif'));
%generate a cell array of names
names = {file_S.name};
%% Parse Channel Number by opening first image
info = imfinfo(fullfile(file_S(1).folder, file_S(1).name));
width = info(1).Width;
height = info(1).Height;
num_c = numel(info);
%% Series of strsplit calls to parse number of Z planes
split_cell = cellfun(@(x) strsplit(x, '_'), names, 'UniformOutput', false);
tail_cell = cellfun(@(x) strsplit(x{end}, 'z'), split_cell, 'UniformOutput', false);
z_cell = cellfun(@(x) strsplit(x{end}, '.'), tail_cell, 'UniformOutput', false);
z_array = cellfun(@(x) str2double(x{1}), z_cell);
num_z = max(z_array);