function s = radialDispStruct(structMatfile, classMatfile)
%%radialDispStruct Creates a structural array containing all the
%%information needed to calculate radial displacements of foci reative to
%%spindle axis
%
%   inputs :
%       structMatfile : A string variable pointing to the matfile
%       contianing the structure array generated by filterStruct.
%
%       classMatfile : A string variable pointing to the matfile containing
%       the cell array generated by userClass app.
%
%   output :
%       s : A structure array contianing the following fields:
%           s.allDataCell : The cell array outputted by aggImages function
%
%           s.filterCell : A cell array filtered by the spindle length,
%           specified by spindleBounds, and zTilt.
%
%           

%% Load in the data from the matfiles
load(structMatfile, 's');
load(classMatfile, 'outCell');

%% Apply outCell classifications to s.filterCell
classLabels = outCell(:,2);
classLabels = cell2mat(classLabels);
classLabels = [1; classLabels];
binLabels = boolean(classLabels);
if size(binLabels,1) ~= size(s.filterCell, 1)
    error('Mismatch in size of outCell and s.filtercell');
end
s.classCell = s.filterCell(binLabels, :);
%% Apply rotation to s.classCell
[s.rotCell,s.Y] =  rotateAllCoords(s.classCell, s.spbChannel);
s.absY = abs(s.Y);
s.absYnm = s.absY * s.pixelSize;